version: "3.4"

services:
  couchdb:
#    environment:
#      COUCHDB_USER: "admin"
#      COUCHDB_PASSWORD: "password"
    image: couchdb:2.1.1
    networks:
      - docker-net

  redis:
    image: redis:3.2.11-alpine
    networks:
      - docker-net

  app:
    depends_on:
      - couchdb
      - redis
    environment:
      COZY_ADMIN_HOST: 0.0.0.0
      COZY_DOMAIN: cozy.docker
      COZY_COUCHDB_URL: "http://couchdb:5984/"
      DEBUG: "true"
    image: xylphid/cozy-stack:latest
    labels:
      traefik.enable: "true"
      traefik.backend: "Cozy"
      traefik.admin.frontend.headers.SSLRedirect: "true"
      traefik.admin.frontend.rule: "Host:cozy-adm.docker"
      traefik.admin.port: "6060"
      traefik.drive.frontend.headers.SSLRedirect: "true"
      traefik.drive.frontend.rule: "HostRegexp:cozy.docker,{subdomain:[a-z]+}.cozy.docker"
      traefik.drive.port: "8080"
    networks:
      - docker-net
    ports:
      - 8081:8080
      - 6060:6060
    restart: always

networks:
  docker-net:
    external: true